### ISSUE TITLE
Install does not work with relative paths

### ISSUE THREAD

**Issue by milasudril** [natecraddock/AddonDevelopmentTool#8]
```
Traceback (most recent call last):
  File "/home/torbjorr/.config/blender/2.77/scripts/addons/AddonDevTool.py", line 515, in execute
    zip_project(temp + os.sep + addon_name + ".zip", project_files, path, addon_name)
  File "/home/torbjorr/.config/blender/2.77/scripts/addons/AddonDevTool.py", line 185, in zip_project
    zip.write(path + file, name + os.sep + file)
  File "/usr/lib/python3.5/zipfile.py", line 1433, in write
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '//__init__.py'

location: <unknown location>:-1
```

**Comment by natecraddock** [comment]
I will take a look at this. I am pretty sure I added code to convert all paths to absolute, but maybe I missed it somewhere. For now, you can just choose the location of your addon, and make it absolute.
